---
title: "R Notebook"
output: html_notebook
---

```{r setup}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
devtools::load_all()
library(tidyverse)
library(here)

#mexp <- readRDS(here(".testing/HealthyAthletes/output", paste0("P20036_HealthyAthletes_Baker2_MiQARreport.rds")))
mexp <- readRDS(here(".testing/AIBL/output", paste0("AIBL_BATCH-2-1-4_FINAL_DriftBatchCorrected_MidarExp_2023-03-07.rds")))
```

```{r, fig.retina=2}
qc_types <- c("SPL", "TQC", "BQC", "NIST")
qc_colors <- c("SPL" = "#135480", "TQC" = "blue", "BQC" = "red", "NIST"="green4")
qc_fill <- c("SPL" = "#0b324d", "TQC" = "darkblue", "BQC" = "red", "NIST"="#b0f7b3")
dd <- mexp@dataset |> 
  select(RUN_ID, ANALYSIS_ID, FEATURE_NAME, QC_TYPE, Intensity, Concentration) |> 
  filter(QC_TYPE %in% qc_types) 

dd$QC_TYPE <- forcats::fct_relevel(dd$QC_TYPE, qc_types)

dd_filt <- dd |> 
  arrange(QC_TYPE) |>
  filter(FEATURE_NAME == "PC 34:2") |> 
  filter(QC_TYPE != "NIST") |> 
  mutate(Value = Concentration) |> #as.double(ntile(Concentration, n=140))) |> 
  #mutate(Value = as.double(ntile(Concentration, n=40))) |> 
  mutate(RUN_ID = as.double(ntile(RUN_ID, n=60)))

p <- ggplot(dd_filt , aes(x=RUN_ID, y=Value, color = QC_TYPE,fill = QC_TYPE)) + 
  #geom_bin_2d(size =10, bins = 30, alpha = .1, linewidth = 0.1)+
  #geom_hex(data = dd_filt |> filter(QC_TYPE %in% c("BQC","TQC", "NIST", "SPL")), aes(x=RUN_ID, y=Value, color = QC_TYPE,fill = QC_TYPE),size =40, bins = 11, alpha = .4, linewidth = 0.1)+
  geom_point(data = dd_filt |> filter(QC_TYPE =="SPL"), size =2, alpha = 0.1, stroke=0.1, shape = 21) +
  ggfx::with_shadow(geom_point(data = dd_filt |> filter(QC_TYPE %in% c("BQC", "NIST")), aes(x=RUN_ID, y=Value, color = QC_TYPE,fill = QC_TYPE), size =3, alpha = .6, stroke=1.11, shape = 21), x_offset = 3.5, y_offset = 3.5, sigma = 1.4, colour = "grey89") +
  scale_color_manual(values = qc_colors) +
  scale_fill_manual(values = qc_fill) + 
  theme_void()

p

#ggsave(filename = "test.png", p, width = 12, height = 7, dpi = 300)
```

```{r}
ggsave(filename = "test.png", p, width = 12, height = 7, dpi = 300)

ibrary(purrr)

# define a function that takes a data frame and an index as input
my_function <- function(df, i) {
subset(df, select = y) %>%
set_names(paste0("y_", i))
}

# apply the function to each element of the list using imap()
result <- imap(my_list, my_function)

# print the result```
```
