comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 80%
        informational: true
    patch:
      default:
        target: auto
        threshold: 80%
        informational: true
