---
title: "MiQAR"
output: html_notebook
---


```{R}

devtools::load_all()
```

```{r setup}
# Do not forget to update midar: remotes::install_github("SLINGhub/midar")

#library(midar)
library(here)
library(tidyverse)
library(conflicted)
library(dplyr)
```

## Proccess

```{r}
mexp <- MidarExperiment()

mexp <- read_MRMkit_results(mexp, raw_area_file = here(".testing/Rachel/OHCA/data/OHCA_FFP_quant_raw_noBQC3TQC3BQC6.tsv"), final_results_file = "")
mexp <- loadMSOrganizerXLM(data = mexp, filename = here(".testing/Rachel/OHCA/data/MSTemplate_Creator_FFP_OHCA_BB_noBQC3TQC3BQC6_corr.xlsm"))

mexp <- normalize_by_istd(mexp)
mexp <- quantitate_by_istd(mexp)
mexp <- calculate_qc_metrics(mexp)

mexp <- apply_qc_filter(
  data = mexp,
  CV_BQC_max = 30,
  Intensity_BQC_min = 100,
  SB_RATIO_min = 5,
  R2_min = 0.8,
  RQC_CURVE = "A")


mexp_final <- mexp # For now this is our final data

# # Drift correction WITHIN batch
# mexp_final<- drift_corr_loess(
#   data = mexp,
#   qc_types = c("TQC"),
#   smooth_by_batch = TRUE, loess_span = 0.75, apply_only_if_smpl_cv_lower = FALSE, treshold_smpl_cv_delta = 0)
#  
# # BETWEEN-batch median centering (applies to all species only currently)
mexp_final <- batch_corr_center(data = mexp_final, qc_types = c("BQC"), center_by_fun = "median")
mexp_final@dataset$Concentration <- mexp_final@dataset$CONC_FINAL
mexp_final@dataset <- mexp_final@dataset |> ungroup()
mexp_final <- calculate_qc_metrics(mexp_final)

mexp_final <- apply_qc_filter(
  data = mexp_final,
  CV_BQC_max = 30,
  Intensity_BQC_min = 100,
  SB_RATIO_min = 5,
  R2_min = 0.8,
  RQC_CURVE = "B")


rr <- setdiff(mexp_final@dataset_QC_filtered$FEATURE_NAME |> unique(), 
              mexp@dataset_QC_filtered$FEATURE_NAME |> unique())
print(paste0("Following species were 'recovered' by the batch correction: ", paste0(rr, collapse = ", ")))


writeReportXLS(data = mexp_final, filename = here("output/Rachel_OHCA_MiQARreport_noBQC3TQC3BQC6_CV30_SB5_corr.xlsx"))
```

# Plots

```{r warning=FALSE}
# Raw areas
midar::plot_runscatter(
  data = mexp_final, y_var = "Intensity", transition_filter = "",show_driftcorrection = FALSE,QC_TYPE_fit = "BQC",
  show_batches = TRUE, batches_as_shades = FALSE, after_correction = FALSE, 
  cap_values = TRUE,cap_SPL_SD = 3, cap_QC_SD = 3,cap_top_n = 1,
  cols_page = 5, rows_page = 4,point_size = 1.5,point_transparency = 0.8,point_stroke_width = 1,
  annot_scale = 0.8, batch_line_color = "grey40",
  outputPDF = TRUE, filename = here("output/Rachel_OHCA_rawAREA_noBQC3TQC3BQC6,pdf"), return_plot_list = FALSE)

# Concentrations
midar::plot_runscatter(
  data = mexp, y_var = "Concentration", transition_filter = "IS",filter_exclude = TRUE, show_driftcorrection = FALSE,QC_TYPE_fit = "TQC",
  show_batches = TRUE, batches_as_shades = FALSE, after_correction = FALSE, 
  cap_values = TRUE,cap_SPL_SD = 3, cap_QC_SD = 3,cap_top_n = 1,
  cols_page = 5, rows_page = 4,point_size = 1.5,point_transparency = 0.8,point_stroke_width = 1,
  annot_scale = 0.8, batch_line_color = "grey40",
  outputPDF = TRUE, filename = here("output/Rachel_OHCA_rawCONC_noBQC3TQC3BQC6_CV30_SB5_RAW-CONC.pdf"), return_plot_list = FALSE)

# Concentrations BATCH corrected
midar::plot_runscatter(
  data = mexp_final, y_var = "Concentration", transition_filter = "IS",filter_exclude = TRUE, show_driftcorrection = FALSE,QC_TYPE_fit = "TQC",
  show_batches = TRUE, batches_as_shades = FALSE, after_correction = FALSE, 
  cap_values = TRUE,cap_SPL_SD = 3, cap_QC_SD = 3,cap_top_n = 1,
  cols_page = 5, rows_page = 4,point_size = 1.5,point_transparency = 0.8,point_stroke_width = 1,
  annot_scale = 0.8, batch_line_color = "grey40",
  outputPDF = TRUE, filename = here("output/Rachel_OHCA_ADJ-CONC_BATCHcorr_noBQC3TQC3BQC6_CV30_SB5_adjCONC.pdf"), return_plot_list = FALSE)

midar::plot_responsecurves(
  data = mexp_final, 
  output_PDF = TRUE,
  pdf_file_name = here("output/Rachel_OHCA_MiQARresponse_noBQC3TQC3BQC6_CV30_SB5_corr.pdf"),
  response_variable = "Intensity", 
  regr_max_percent = 200, 
  include_features_containing = "", 
  exclude_features_containing = "")


plot_pca_qc(mexp_final,variable = "Concentration", log_transform = TRUE, dim_x = 1, dim_y = 2, grouping = TRUE, fill_alpha = .1)
```

```{r}

```
