---
title: "R Notebook"
output: html_notebook
---

```{r}
devtools::load_all()
library(here)
library(tidyverse)
#library(midar)
```
```{r}
d_lims_db <- readxl::read_excel(here(".testing/AIBL/data/P21011_LIMS_WorklistResultList_bo_Nov-25-2022-04-35-20.xls"),sheet = "Analytical Results", trim_ws = TRUE) |> 
  dplyr::select(ANALYSIS_ID = Datafilename, QC_TYPE = `QC Sample Type`, EXT_ID = `External Sample ID`, 
                dplyr::everything()) |> 
  mutate(ExternalID = stringr::str_squish(EXT_ID))

d_sample_metadata <- readxl::read_excel(here(".testing/AIBL/data/ProteinConc_in_50ul_AIBL_platelets_FL_2022-12-01.xlsx"), 
                                        sheet = "ug_per_50uL",  trim_ws = TRUE) |>
  dplyr::select(EXT_ID = `External Sample ID`, protein_conc, protein_conc_low) |>
  mutate(ExternalID = stringr::str_squish(EXT_ID))

d_prot <- d_lims_db |>  dplyr::select(ANALYSIS_ID, QC_TYPE, EXT_ID) |> left_join(d_sample_metadata |> dplyr::select(EXT_ID, protein_conc)) |> 
  mutate(ANALYSIS_ID = str_remove(ANALYSIS_ID, ".d"))

```

```{r}
devtools::load_all()
mexp2 <- MidarExperiment()

mexp2 <- loadMasshunterCSV(mexp2, 
  filename = here(".testing/AIBL/data/AIBL_Batch2_CombineAllgroups_lipids_FLBB.csv"))

mexp2 <- loadMSOrganizerXLM(mexp2, here(".testing/AIBL/data/AIBL_Metadata_Batch2_AllGroups_FL.xlsm"))
mexp2 <- normalize_by_istd(mexp2) 


mexp2@annot_analyses <- mexp2@annot_analyses  |> 
  left_join(d_prot) |> 
  mutate(SAMPLE_AMOUNT = if_else(is.na(SAMPLE_AMOUNT), protein_conc, SAMPLE_AMOUNT))
mexp2 <- quantitate_by_istd(mexp2) 

mexp2 <- drift_corr_loess(mexp2, qc_types = c("TQC"), smooth_by_batch = TRUE, log2_transform = TRUE, loess_span = 0.75, 
                          apply_only_if_smpl_cv_lower = TRUE)

mexp2b <- mexp2
mexp2b@dataset$Concentration = mexp2b@dataset$CONC_FINAL

mexp2b <- calculate_qc_metrics(mexp2b)

mexp2b <- apply_qc_filter(
  data = mexp2b, 
  Intensity_BQC_min = 300,
  CV_BQC_max = 25,
  SB_RATIO_min = 3,
  R2_min = 0.8,
  RQC_CURVE = 1 
)

```


```{r}
#devtools::load_all()
mexp1 <- MidarExperiment()

mexp1 <- loadMasshunterCSV(mexp1, 
  filename = here(".testing/AIBL/data/AIBL_Batch1_Repeat_compileAllGroups_FL.csv"))

mexp1 <- loadMSOrganizerXLM(mexp1, here(".testing/AIBL/data/AIBL_Metadata_Batch1_AllGroups_Repeat_FL.xlsm"))
mexp1 <- normalize_by_istd(mexp1) 

mexp1@annot_analyses <- mexp1@annot_analyses  |> 
  left_join(d_prot) |> 
  mutate(SAMPLE_AMOUNT = if_else(is.na(SAMPLE_AMOUNT), protein_conc, SAMPLE_AMOUNT))
mexp1 <- quantitate_by_istd(mexp1) 

mexp1 <- drift_corr_loess(mexp1, qc_types = c("TQC"), smooth_by_batch = TRUE, log2_transform = TRUE, loess_span = 0.75, 
                          apply_only_if_smpl_cv_lower = TRUE)

mexp1b <- mexp1
mexp1b@dataset$Concentration = mexp1b@dataset$CONC_FINAL

mexp1b <- calculate_qc_metrics(mexp1b)

mexp1b <- apply_qc_filter(
  data = mexp1b, 
  Intensity_BQC_min = 300,
  CV_BQC_max = 25,
  SB_RATIO_min = 3,
  R2_min = 0.8,
  RQC_CURVE = 1 
)

```


```{r}
#devtools::load_all()
mexp3 <- MidarExperiment()

mexp3 <- loadMasshunterCSV(mexp3, 
  filename = here(".testing/AIBL/data/AIBL_Batch3_CombineAllgroups_lipids_FL.csv"))

mexp3 <- loadMSOrganizerXLM(mexp3, here(".testing/AIBL/data/AIBL_Metadata_Batch3_AllGroups_FL.xlsm"))
mexp3 <- normalize_by_istd(mexp3) 

mexp3@annot_analyses <- mexp3@annot_analyses  |> 
  left_join(d_prot) |> 
  mutate(SAMPLE_AMOUNT = if_else(is.na(SAMPLE_AMOUNT), protein_conc, SAMPLE_AMOUNT))
mexp3 <- quantitate_by_istd(mexp3) 

mexp3 <- drift_corr_loess(mexp3, qc_types = c("TQC"), smooth_by_batch = TRUE, log2_transform = TRUE, loess_span = 0.75, 
                          apply_only_if_smpl_cv_lower = TRUE)

mexp3b <- mexp3
mexp3b@dataset$Concentration = mexp3b@dataset$CONC_FINAL

mexp3b <- calculate_qc_metrics(mexp3b)

mexp3b <- apply_qc_filter(
  data = mexp3b, 
  Intensity_BQC_min = 300,
  CV_BQC_max = 25,
  SB_RATIO_min = 3,
  R2_min = 0.8,
  RQC_CURVE = 1 
)

```

```{r}
#devtools::load_all()
mexp4 <- MidarExperiment()

mexp4 <- loadMasshunterCSV(mexp4, 
  filename = here(".testing/AIBL/data/AIBL_Batch4_CombineGPs_Lipids_FL.csv"))

mexp4 <- loadMSOrganizerXLM(mexp4, here(".testing/AIBL/data/AIBL_Metadata_Batch4_AllGroups_FL.xlsm"))
mexp4 <- normalize_by_istd(mexp4) 

mexp4@annot_analyses <- mexp4@annot_analyses  |> 
  left_join(d_prot) |> 
  mutate(SAMPLE_AMOUNT = if_else(is.na(SAMPLE_AMOUNT), protein_conc, SAMPLE_AMOUNT))
mexp4 <- quantitate_by_istd(mexp4) 

mexp4 <- drift_corr_loess(mexp4, qc_types = c("TQC"), smooth_by_batch = TRUE, log2_transform = TRUE, loess_span = 0.75, 
                          apply_only_if_smpl_cv_lower = TRUE)

mexp4b <- mexp4
mexp4b@dataset$Concentration = mexp4b@dataset$CONC_FINAL

mexp4b <- calculate_qc_metrics(mexp4b)

mexp4b <- apply_qc_filter(
  data = mexp4b, 
  Intensity_BQC_min = 300,
  CV_BQC_max = 25,
  SB_RATIO_min = 3,
  R2_min = 0.8,
  RQC_CURVE = 2 
)

```



```{r message=FALSE, warning=FALSE}
##### 
p <- plot_runscatter(
  data = mexp,
  y_var = "Intensity", 
  cap_values = TRUE,
  cap_top_n = 20,
  cap_SPL_SD =5 ,
  cap_QC_SD = 3,
  QC_TYPE_fit = "BQC", 
  transition_filter = "",
  filter_exclude = FALSE,
  show_driftcorrection = FALSE,
  after_correction = FALSE, 
  show_batches = TRUE,
  batches_as_shades = FALSE,
  batch_line_color = "bisque2"  ,
  batch_shading_color = "grey80", 
  outputPDF = TRUE,
  filename = here(".testing/output", paste0("AIBL_FL_Baker_Baker-Batch3_MiQAR_RAW-AREA_", Sys.Date(), "_V1.pdf")),
  cols_page = 5,
  rows_page = 4,
  point_size = 0.5,
  annot_scale = .75,
  paper_orientation  = "LANDSCAPE",
  point_transparency = 0.86, 
  page_no = NA,
  silent = FALSE, 
  return_plot_list = FALSE)

```

```{r}
plot_responsecurves(
  data = mexp,
  response_variable = "Intensity", 
  output_PDF = TRUE,
  pdf_file_name = here(".testing/output", paste0("AIBL_FL_Baker-Batch4_MiQAR_RQCCURVES_", Sys.Date(), "_V1.pdf")),
  include_features_containing = "",
  exclude_features_containing = "",
  regr_max_percent = 100, 
  columns_page = 6,
  rows_page = 5,
  point_size = 1.0,
  line_width = 0.5,
  text_scale_factor = 0.8,
  return_plot_list = FALSE
)
```

```{r}

devtools::load_all()

mexp_all <- combine_experiments(mexp2b, mexp1b, mexp4b, ordered_by_runsequence = TRUE)
mexp_all@annot_batch_info <- mexp_all@annot_batch_info |> mutate(BATCH_ID = row_number())

mexp_all@dataset <- mexp_all@dataset |> filter(QC_TYPE != "RQC")

mexp_all <- batch_corr_center(data = mexp_all, qc_types = "TQC", center_by_fun = "median")

mexp_all@dataset <- mexp_all@dataset |> arrange(RUN_ID) |>  group_by(FEATURE_NAME) |> mutate(RUN_ID = row_number())


mexp_all <- calculate_qc_metrics(mexp_all)

mexp_all <- apply_qc_filter(
  data = mexp_all, 
  Intensity_BQC_min = 300,
  CV_BQC_max = 25,
  SB_RATIO_min = 3,
  R2_min = 0.8,
  RQC_CURVE = 2 
)

writeReportXLS(mexp_all, here(".testing/output", paste0("AIBL/AIBL_BATCH-2-1-4_MiQARreport_", Sys.Date(), "_V1.xlsx")))

d_exp <- mexp_all@dataset_QC_filtered |> 
  filter(!str_detect(FEATURE_NAME, "\\(IS"), QC_TYPE == "SPL") |> 
  left_join(d_prot, by = "ANALYSIS_ID") |> 
  select(EXT_ID, FEATURE_NAME, Concentration) |> 
  filter(!EXT_ID %in% c("0462 KG__36m" , "0395 AC__54m", "0915 JR__72m", "0915 JR__54m", "0413 AS__36m")) |> 
  pivot_wider(names_from = "FEATURE_NAME", values_from = "Concentration")

write_csv(d_exp, here(".testing/output", paste0("AIBL/AIBL_BATCH-2-1-4_FINAL_DriftBatchCorrected_pmol_ug_protein_", Sys.Date(), "_V2.csv")))

saveRDS(object = mexp_all, file = here(".testing/AIBL/output", paste0("AIBL_BATCH-2-1-4_FINAL_DriftBatchCorrected_MidarExp_", Sys.Date(), ".rds")))


rr <- mexp_all@dataset |> 
  filter(QC_TYPE == "SPL") |> 
  group_by(FEATURE_NAME) |> 
  summarise(RT=median(RT), PRECURSOR_MZ = median(PRECURSOR_MZ), median(PRODUCT_MZ))

write_csv(rr, here(".testing/output", paste0("AIBL/AIBL_RT_MZ_list_", Sys.Date(), "_V2.csv")))
```

```{r message=FALSE, warning=FALSE}
##### 
p <- plot_runscatter(
  data = mexp_all,
  y_var = "normIntensity", 
  cap_values = TRUE,
  cap_top_n = 20,
  cap_SPL_SD =5 ,
  cap_QC_SD = 3,
  QC_TYPE_fit = "BQC", 
  transition_filter = "",
  filter_exclude = FALSE,
  show_driftcorrection = FALSE,
  after_correction = FALSE, 
  show_batches = TRUE,
  batches_as_shades = TRUE,
  batch_line_color = "bisque2"  ,
  batch_shading_color = "grey80", 
  outputPDF = TRUE,
  filename = here(".testing/output", paste0("AIBL_BakerPanel_BATCH-2-1-4_NormINTENSITY_", Sys.Date(), "_V1.pdf")),
  cols_page = 5,
  rows_page = 4,
  point_size = 0.5,
  annot_scale = .75,
  paper_orientation  = "LANDSCAPE",
  point_transparency = 0.86, 
  page_no = NA,
  silent = FALSE, 
  return_plot_list = FALSE)

```
```{r}
qplot(x = mexp1b@d_QC$Int_med_BQC *30, y =  mexp1b@d_QC$conc_CV_BQC) + scale_y_continuous(limits = c(0,50))+
  scale_x_log10() + geom_smooth() + theme_bw() + labs(x = "Peak Area BQC", y="%CV of BQC")
```

