---
title: "Data Identifiers in MiDAR"
output: 
  rmarkdown::html_vignette:
    fig_width: 6
    fig_height: 2
description: |
  MiDAR: Postprocessing and Quality Control of Small-Molecule Mass Spectrometry Data 
vignette: >
  %\VignetteIndexEntry{Data Identifiers in MiDAR}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
editor_options: 
  markdown: 
    wrap: 80
bibliography: references.bib
---

```{r, include = FALSE, echo = FALSE}
knitr::opts_chunk$set(collapse = TRUE, results = FALSE, warning = FALSE,
                      message = FALSE, comment = "#>", out.width = "100%")
set.seed(1041)
options(dplyr.print_max = 10)
```

## Key Data Identifiers

The following key data fields are essential for organizing data in `MiDAR`. These 
data key fields are used in organizing the data within the `MidarExperiment` object
and some functions in the `MiDAR` package employ these fields.

| Table | Field | Description |
|---------------------------|---------------------------|---------------------------|
| Analyses | [`analysis_id`]{style="color: blue;"} | Unique identifier of each analysis. |
|  | `qc_type` | QC/Sample type, see next section. |
|  | `batch_id` | Unique identifier of each batch level. |
|  | sample_id | Unique identifier pf the (physical) sample that was tested |
| Features | [`feature_id`]{style="color: blue;"} | Unique identifier for each feature. |
|  | `istd_feature_id` | The `feature_id` of the internal standard used to normalize raw intensities (each internal standard must be defined as a feature). |
|  | analyte_id | Unique identifier of the analyte |

Certain field names differ from conventional terminology
(e.g., `analysis_id` instead of `sample_id`) to allow more flexible workflows
and to reduce confusion with other identifiers. A sample may be measured
multiple times across different methods or processing replicates, necessitating
distinct identifiers. Similarly, analytes can be quantified through multiple
transitions or adducts, which is why `feature_id` is designated as the primary
identifier.

## QC types (Sample Types)

QC types categorize samples based on their analytical purpose and are utilized
throughout various functions in the MiDAR package. This classification system
combines nomenclature from multiple sources: several standardized terms (SPL,
BQC, TQC, LTR, RQC) were introduced by
@broadhurst2018GuidelinesConsiderationsUse in "Guidelines and considerations for
the use of system suitability and quality control samples in mass spectrometry
assays," while others (LQC, MQC, HQC, CAL, NIST, SST, and various blank types)
derive from traditional terminology in analytical and clinical chemistry. The
integration of these nomenclature systems provides a comprehensive framework for
quality control in analytical workflows.

| QC type | Group | Description |
|---------|----------------------|--------------------------------|
| SPL | Unknowns | Study sample ('unknowns') |
| BQC | QC | Batch/Process QC |
| TQC | QC | Technical QC |
| LQC | QC | Low QC |
| MQC | QC | Mid QC |
| HQC | QC | High QC |
| CAL | Calibration | Calibration sample |
| RQC | QC | Response QC |
| LTR | Reference Material | Long-Term Reference |
| NIST | Reference Material | NIST Standard Reference Material |
| SST | QA | System Suitability Test Sample |
| PBLK | Process Blank | No matrix, processed with ISTD as all other samples |
| UBLK | Blank | Unextrated Blank. No matrix, with ISTD without undergoing sample processing |
| SBLK | Blank | Solvent Blank/double Blank, no matrix, no ISTD, just solvents |
| IBLK | Blank | Instrument Blank with/without injection |
| MBLK | Blank | Matrix Blank. Matrix processed as samples without ISTDs |

QC type is represented with a consistent color scheme (both fill and line
colors) and specific point shapes in all plots generated by the MiDAR package.
This visual coding allows consistent identification and comparison of different
QC types across various visualizations.

## References
