---
title: "Drift and Batch Correction"
output: 
  rmarkdown::html_vignette:
    fig_width: 6
    fig_height: 2
vignette: >
  %\VignetteIndexEntry{Drift and Batch Correction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
editor_options: 
  markdown: 
    wrap: 100
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)


```

First, we start with loading {midar} package and importing the data.

```{r setup}
#| results: false  
#| message: false
library(midar)

myexp <- midar::MidarExperiment()
myexp <- import_data_csv(
  data = midar::MidarExperiment(),
  path = "batch_effect-simdata-u1000-sd100_7batches.csv", 
  variable_name = "conc", 
  import_metadata = TRUE)
```

## Batch-Centering

```{r}
#| results: false  
#| code-overflow: 'wrap'

# Correct batch effects - Set `correct_scale = TRUE` to scale also variance
myexp <- correct_batch_centering(
  data = myexp, 
  variable = "conc",
  ref_qc_types = "SPL", 
  correct_scale = FALSE)

```

Now let's plot the data before and after batch correction.

```{r}
#| results: false 
plot_runscatter(myexp, variable = "conc_before", rows_page = 1, cols_page = 1)
plot_runscatter(myexp, variable = "conc", rows_page = 1, cols_page = 1)
```

Next, we correct the batch effects again, this time with scaling of variance. 

```{r}
#| results: false 
# Correct batch effects - WITH scaling of variance
myexp <- midar::correct_batch_centering(
  myexp, 
  ref_qc_types = "SPL", 
  variable = "conc",
  correct_scale = TRUE)

plot_runscatter(myexp, variable = "conc", rows_page = 1, cols_page = 1)

```

Finally, we can export the corrected data using the `save_dataset_csv()` function.


## Drift Correction and Batch-Centering

```{r}
#| results: false  

# Created a data object
myexp <- midar::MidarExperiment(title = "batch-effects")

# Import a wide CSV file with some metadata 
myexp <- import_data_csv(data = myexp, 
                          path = "drift_batch_effect-simdata-u1000-sd100_7batches.csv", 
                          variable_name = "conc", 
                          import_metadata = TRUE)

# Within-batch drift correction (smoothing) based on study samples
myexp <- midar::correct_drift_gaussiankernel(myexp,
                                        variable = "conc",
                                        ref_qc_types = "SPL", 
                                        batch_wise = TRUE, 
                                        kernel_size = 10, 
                                        recalc_trend_after = TRUE,show_progress = T)

# Plot before and after batch correction 
plot_runscatter(myexp, variable = "conc_before", rows_page = 1, cols_page = 1, 
                          show_trend = TRUE, show_progress = F)
plot_runscatter(myexp, variable = "conc", rows_page = 1, cols_page = 1, 
                          show_trend = TRUE, show_progress = F)

# Correct between-batch effects (median centering)
myexp <- midar::correct_batch_centering(myexp, 
                                        variable = "conc",
                                        ref_qc_types = "SPL", 
                                        correct_scale = TRUE)
#Plot again the fully corrected data
plot_runscatter(myexp, variable = "conc", rows_page = 1, cols_page = 1, 
                          show_trend = TRUE, show_progress = F)


# Save corrected data
midar::save_dataset_csv(myexp, 
                        path = "corrected-data.csv", 
                        variable = "conc", 
                        filter_data = FALSE)
```
