---
title: "R Notebook"
output: html_notebook
---

```{r}
#devtools::load_all()

#library(midar)

# Get paths of example files included with this package
masshunter_file <- system.file("extdata", "Example_MHQuant_1.csv", package = "midar", mustWork = TRUE)
metadata_file <- system.file("extdata", "Example_Metadata_1.xlsm", package = "midar", mustWork = TRUE)

mexp <- MidarExperiment()

mexp <- read_masshunter_csv(data = mexp, filename = masshunter_file)
mexp <- read_msorganizer_xlm(data = mexp, filename = metadata_file)
mexp <- normalize_by_istd(mexp)
mexp <- quantitate_by_istd(mexp)

mexp <- calculate_qc_metrics(mexp)

mexp <- apply_qc_filter(data = mexp,
                        CV_BQC_max = 30,
                        Intensity_BQC_min = 100,
                        SB_RATIO_min = 5,
                        R2_min = 0.8,
                        RQC_CURVE = 1)
```


```{r}
plot_responsecurves(data = mexp, output_PDF = TRUE,response_variable = "Intensity", regr_max_percent = 100, pdf_file_name = "rqc.png",rows_page = 5,columns_page = 5,return_plot_list = FALSE)
```

