---
title: "Daniel"
subtitle: "Data Analysis"
author: "SingMass"
output: html_document
date: "2023-02-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(here)
library(patchwork)
library(scales)
devtools::load_all()
```

```{r data-import}
d_orig <- read_xlsx(here(".testing/FTT/SingMass-Endofotonics/data/Tissue_Endofotonics_Report 20230114.xlsx"), 
                    sheet = "FinalResults CSV", 
                    trim_ws = TRUE)

d_metadata <- read_xlsx(here(".testing/FTT/SingMass-Endofotonics/data/SNUH samples Info.xlsx"), 
                    sheet = "SampleInfo Curated (BB)", 
                    trim_ws = TRUE) |> 
  filter(ExpGroup != "EFX")

d_long <- d_orig |> 
  rename(FEATURE_NAME = Name) |> 
  filter(!is.na(FEATURE_NAME)) |>  # Remove rows with other info (protein conc etc)
  pivot_longer(-FEATURE_NAME, names_to = "ANALYSIS_ID", values_to = "Concentration") |> 
  filter(!str_detect(FEATURE_NAME, "IS")) 
  


```


```{r}
d_datannot <- d_long |> inner_join(d_metadata, by = c("ANALYSIS_ID"="SAMPLE_ID")) |> 
  filter(ExpGroup != "EFX")

devtools::load_all()
d_stats <- get_stats(d_datannot, feature = "FEATURE_NAME", grouping = "ExpGroup", group_case = "EF1", group_ref = "EF0", paired = TRUE)
p_volcano1 <- volcano_plot(d_FC = d_stats, p_adjust = FALSE, sig_FC_min = 1.5, sig_p_value_min = 0.05, symmetric_x = TRUE, point_size = 1, point_transparency = 0.5, scale_factor = 1, scale_factor_species_label = .5, axistick = 1)

p_fig1 <- (p_volcano1 + ggtitle("EF 1 vs EF 0 (paired t test)"))

ggsave(filename = "volcano1a.png",  plot = p_fig1, width = 200, height = 100, units = "mm", dpi = 600)

```

```{r heatmap}

annot_colors <- list(
  ExpGroup = c("EF0" = "cyan3", "EF1" = "red")
)


p_hm <- plot_heatmap(data = d_long, d_metadata = d_metadata |>  select(ANALYSIS_ID = SAMPLE_ID, ExpGroup), 
                     annot_color = annot_colors, log_transform = FALSE, split_variable = NULL, 
                     clust_rows = FALSE, clust_columns = TRUE,row_names_size = 3, col_names_size = 8) 

png(file="heatmap.png", width=150,height=250 ,units="mm",res=600)
draw(p_hm)
dev.off()
```

```{r pca}
p_pca1 <- plot_pca_sling2(data = d_long, d_metadata = d_metadata |>  select(ANALYSIS_ID = SAMPLE_ID, ExpGroup), log_transform = FALSE, dim_x = 1, dim_y = 2, grouping = "ExpGroup", annot_color = annot_colors$ExpGroup, point_size = 4, fill_alpha = 0.05, ellipse = TRUE, mark_ellipse = FALSE) 

p_pca2 <- plot_pca_sling2(data = d_long, d_metadata = d_metadata |>  select(ANALYSIS_ID = SAMPLE_ID, ExpGroup), log_transform = FALSE, dim_x = 3, dim_y = 4, grouping = "ExpGroup", annot_color = annot_colors$ExpGroup, point_size = 4, fill_alpha = 0.05, ellipse = TRUE, mark_ellipse = FALSE)

ggsave(filename = "pca.png",  plot = p_pca1 + p_pca2, width = 200, height = 100, units = "mm", dpi = 600)
library(plotly)
ggplotly(p_pca1)
```

```{r}
devtools::load_all()
d_metadata$ExpGroup <- forcats::fct_relevel(d_metadata$ExpGroup, c("EF0", "EF1"))
d_metadata$Exp <- "A"
d_metadata$SUBJECT_ID <- factor(d_metadata$StudyNo)
d_metadata$Exp <- factor(d_metadata$Exp)
plot_dotboxplus(data = d_long, d_metadata = d_metadata, inner_group = ExpGroup, outer_group = Exp, 
                contrasts = list(c("EF1", "EF0")), inner_group_colors = annot_colors$ExpGroup, 
                rows_page = 4, columns_page = 5, class_per_page = FALSE, save_pdf = TRUE, filename = "dotplots2.pdf", paired = TRUE, scale_text =1, scale_signf = 2.5)


d_sign <- d_stats |> filter(p_value < 0.05, abs(log2FC) > log2(1.5)) |> select(FEATURE_NAME)

d_long_sign <- d_long |> inner_join(d_sign)

plot_dotboxplus(data = d_long_sign, d_metadata = d_metadata, inner_group = ExpGroup, outer_group = Exp, 
                contrasts = list(c("EF1", "EF0")), inner_group_colors = annot_colors$ExpGroup, 
                rows_page = 4, columns_page = 6, class_per_page = FALSE, save_pdf = TRUE, filename = "dotplots2sigf.pdf", paired = TRUE, scale_text =.7, scale_signf = 1.5)
```

