name: R-CMD-check

on:
  push:
    branches: [main, master, development]
  pull_request:
    branches: [main, master, development]

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest, r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::devtools
            any::remotes
          needs: check

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev

      - name: Install lancer
        run: |
          Rscript -e 'remotes::install_github("SLINGhub/lancer")'

      - name: Install additional dependencies
        run: |
          Rscript -e 'install.packages(c(
            "assertr",
            "dtplyr",
            "forcats",
            "lubridate",
            "readr",
            "openxlsx2",
            "ggh4x",
            "ggvenn",
            "ggbeeswarm",
            "ggsignif",
            "ggforce",
            "ggpmisc",
            "ggnewscale",
            "ggrepel",
            "ComplexHeatmap",
            "bibtex",
            "here"
          ), repos = "https://cloud.r-project.org")'

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-tests", "--no-manual", "--compact-vignettes=gs+qpdf")'
