name: R-CMD-check

on:
  push:
    branches: [main, master, development]
  pull_request:
    branches: [main, master, development]

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest, r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install devtools
        run: |
          Rscript -e 'install.packages("devtools", repos = "https://cloud.r-project.org")'

      - name: Install pak
        run: |
          Rscript -e 'install.packages("pak", repos = "https://cloud.r-project.org")'

      - name: Install lancer from GitHub
        run: |
          Rscript -e 'devtools::install_github("SLINGhub/lancer")'

      - name: Install other dependencies
        run: |
          Rscript -e 'install.packages("sessioninfo", repos = "https://cloud.r-project.org")'
          Rscript -e 'install.packages("rcmdcheck", repos = "https://cloud.r-project.org")'

      - name: Setup R Dependencies
        run: |
          Rscript -e 'pak::pkg_install(c("any::rcmdcheck"), dependencies = TRUE)'
          Rscript -e 'pak::pkg_install(c("devtools", "assertr", "dtplyr", "forcats", "lubridate", "readr", "openxlsx2", "ggh4x", ggvenn,
          "ggbeeswarm"", "ggsignif"", "ggforce"", "ggpmisc"", "ggnewscale"", "ggrepel, "ComplexHeatmap", "ggExtr"', "bibtex", "here"), dependencies = TRUE)'

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--no-tests", "--compact-vignettes=gs+qpdf")'
